name: integracion continua creo 

on: [push]
 

jobs:
  test:

    runs-on: windows-server

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python      
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
